# Generated by Django 3.1.1 on 2022-08-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220819_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.CharField(default=123456, max_length=120),
            preserve_default=False,
        ),
    ]
