# Generated by Django 3.1.1 on 2022-08-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
