# Generated by Django 3.1.1 on 2022-09-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_evidence_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='media',
            new_name='evidence_file',
        ),
    ]
